Completed
Fixed up code based on suggestions, even though the tests still yield 
AttributeError: 'NoneType' object has no attribute 'height',etc:

"BinaryTree comments:
-- is_leaf shouldn't care about "self.value"; it just needs to check the two branches to see if they are None.
-- For size, remember that you'll need to both the left and right branches. Don't return prematurely. Try writing out an example tree diagram and run your function on it.
-- Don't forget your return statements in "contains"
-- For "insert", recall what the "left" and "right" branches are: they're trees. To assign a new value, we'll need to create a new BinaryTree that contains the value to insert (we can't just set left and right to be the value themselves). Your super close though.

Tree comments:
-- For size, don't return prematurely in your "for" loop. Likely, you'll want to sum up the recursive calls and not return them right away. Run through an example too make sure you don't "forget about" any of the branches.
-- For your other "for" loops, make sure you don't return inside them or your function will end without getting to the remaining iterations of the "for" loop. :)
-- get_by_value is super tricky. Really think about what type of data you want to return here. You'll ultimately want to return a Tree (eg, the "self" object!). Recursion is cool."