All recursive and functional, except for peek()
"
Traceback (most recent call last):
  File "python", line 77, in <module>
AttributeError: 'Stack' object has no attribute 'peek'
" 
EXCEPT it is defined as a method of the stack object just like all the other methods which work. I might just need to look at it later with less tired eyes.